name: Docker

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: laravel

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        laravel: [8]
        php: [7.4, 8]

    steps:
      - uses: actions/checkout@v2

      - name: 'Check Laravel and PHP combination'
        run: test -f laravel-${{ matrix.laravel }}/php-${{ matrix.php }}/Dockerfile

      - name: 'Build image'
        run: docker build . --file laravel-${{ matrix.laravel }}/php-${{ matrix.php }}/Dockerfile --tag $IMAGE_NAME

      - name: 'Log into registry'
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 'Push image'
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Set the tag to the laravel and php combination
          VERSION=${{ matrix.laravel }}-php${{ matrix.php }}

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
